[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "segment_tools"
version = "1.0.0"
authors = [  { name="roiro" },]
description = "Segmentation tools"
license = {text = "MIT License"}
requires-python = "==3.10.*"
dependencies = [
    "matplotlib>=3.2.2",
    "opencv-python>=4.6.0",
    "Pillow>=7.1.2",
    "PyYAML>=5.3.1",
    "scipy>=1.4.1",
    "torch>=1.7.0",
    "torchvision>=0.8.1",
    "tqdm>=4.64.0",
    "pandas>=1.1.4",
    "seaborn>=0.11.0",
    # "gradio==3.35.2",
    "ultralytics == 8.0.120",
    "GroundingDINO @ git+https://github.com/qwertyroiro/GroundingDINO_segtools.git",
    "clip @ git+https://github.com/openai/CLIP.git",
    "segment_anything @ git+https://github.com/facebookresearch/segment-anything.git@6fdee8f",
    "transformers",
    "addict",
    "diffusers",
    "huggingface_hub",
    "numpy == 1.23.5",
    "onnxruntime",
    "pycocotools",
    "requests",
    "setuptools",
    "supervision",
    "termcolor",
    "timm",
    "yapf",
    "nltk",
    "fairscale",
    "litellm",
    "accelerate",
    "panopticapi @ git+https://github.com/cocodataset/panopticapi.git",
    "cityscapesscripts @ git+https://github.com/mcordts/cityscapesScripts.git",
    "cython",
    "shapely",
    "h5py == 3.7.0",
    "submitit == 1.4.2",
    "scikit-image",
    "einops == 0.4.1",
    "icecream == 2.1.2",
    "inflect == 5.6.0",
    "diffdist == 0.1",
    "pytorch_lightning == 1.6.4",
    "mmcv == 1.6.2",
    "detectron2 @ git+https://github.com/facebookresearch/detectron2.git",
    # "natten == 0.14.4",
    "imutils"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.hatch.metadata]
allow-direct-references = true