[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "segment_tools"
version = "1.0.0"
authors = [  { name="roiro" },]
description = "Segmentation tools"
license = {text = "MIT License"}
requires-python = "==3.10.*"
dependencies = [
    "matplotlib == 3.8.2",
    "opencv-python == 4.9.0.80",
    "Pillow == 9.3.0",
    "PyYAML == 6.0.1",
    "scipy == 1.12.0",
    "wheel == 0.42.0",
    "torch @ https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=0d4e8c52a1fcf5ed6cfc256d9a370fcf4360958fc79d0b08a51d55e70914df46",
    "torchvision @ https://download.pytorch.org/whl/cu121/torchvision-0.16.0%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=e76e78d0ad43636c9884b3084ffaea8a8b61f21129fbfa456a5fe734f0affea9",
    "tqdm == 4.66.1",
    "pandas == 2.2.0",
    "seaborn == 0.13.2",
    "ultralytics == 8.0.120",
    "GroundingDINO @ git+https://github.com/qwertyroiro/GroundingDINO_segtools.git",
    "clip @ git+https://github.com/openai/CLIP.git@a1d071733d7111c9c014f024669f959182114e33",
    "segment_anything @ git+https://github.com/facebookresearch/segment-anything.git@6fdee8f2727f4506cfbbe553e23b895e27956588",
    "transformers == 4.37.1",
    "addict == 2.4.0",
    "diffusers == 0.25.1",
    "huggingface_hub == 0.20.3",
    "numpy == 1.23.5",
    "onnxruntime == 1.16.3",
    "pycocotools == 2.0.7",
    "requests == 2.31.0",
    "setuptools == 69.0.3",
    "supervision == 0.18.0",
    "termcolor == 2.4.0",
    "timm == 0.9.12",
    "yapf == 0.40.2",
    "nltk == 3.8.1",
    "fairscale == 0.4.13",
    "litellm == 1.20.1",
    "accelerate == 0.26.1",
    "panopticapi @ git+https://github.com/cocodataset/panopticapi.git@7bb4655548f98f3fedc07bf37e9040a992b054b0",
    "cityscapesscripts @ git+https://github.com/mcordts/cityscapesScripts.git@a7ac7b4062d1a80ed5e22d2ea2179c886801c77d",
    "cython == 3.0.8",
    "shapely == 2.0.2",
    "h5py == 3.7.0",
    "submitit == 1.4.2",
    "scikit-image",
    "einops == 0.4.1",
    "icecream == 2.1.2",
    "inflect == 5.6.0",
    "diffdist == 0.1",
    "mmcv == 1.6.2",
    "detectron2 @ git+https://github.com/facebookresearch/detectron2.git@3ff5dd1cff4417af07097064813c9f28d7461d3c",
    "imutils == 0.5.4",
    "rich == 13.7.1",
    "natten @ https://shi-labs.com/natten/wheels/cu121/torch2.1.0/natten-0.15.1%2Btorch210cu121-cp310-cp310-linux_x86_64.whl"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.hatch.metadata]
allow-direct-references = true